# SPDX-FileCopyrightText: 2026 Iva Horn
# SPDX-License-Identifier: MIT

name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build
        run: xcodebuild -project Cirruscope.xcodeproj -target Cirruscope -configuration Release -destination 'platform=macOS' build