# SPDX-FileCopyrightText: 2026 Iva Horn
# SPDX-License-Identifier: MIT

name: REUSE

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  check:
    name: Compliance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v6
