# SPDX-FileCopyrightText: 2026 Iva Horn
# SPDX-License-Identifier: MIT

name: SwiftFormat

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**/*.swift'

jobs:
  Lint:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log
